build: false
clone_folder: c:\projects\maker-bundle

cache:
    - composer.phar
    - .phpunit -> phpunit

init:
    - SET PATH=c:\php;%PATH%

environment:
    TEST_DATABASE_DSN: sqlite:///c:\projects\maker-bundle\tests\tmp\app.db

install:
    - mkdir c:\php && cd c:\php
    - appveyor DownloadFile https://github.com/symfony/binary-utils/releases/download/v0.1/php-7.1.3-Win32-VC14-x86.zip
    - 7z x php-7.1.3-Win32-VC14-x86.zip -y >nul
    - cd ext
    - appveyor DownloadFile https://github.com/symfony/binary-utils/releases/download/v0.1/php_apcu-5.1.8-7.1-ts-vc14-x86.zip
    - 7z x php_apcu-5.1.8-7.1-ts-vc14-x86.zip -y >nul
    - cd ..
    - copy /Y php.ini-development php.ini-min
    - echo memory_limit=-1 >> php.ini-min
    - echo serialize_precision=14 >> php.ini-min
    - echo max_execution_time=1200 >> php.ini-min
    - echo date.timezone="America/Los_Angeles" >> php.ini-min
    - echo extension_dir=ext >> php.ini-min
    - copy /Y php.ini-min php.ini-max
    - echo zend_extension=php_opcache.dll >> php.ini-max
    - echo opcache.enable_cli=1 >> php.ini-max
    - echo extension=php_openssl.dll >> php.ini-max
    - echo extension=php_apcu.dll >> php.ini-max
    - echo apc.enable_cli=1 >> php.ini-max
    - echo extension=php_intl.dll >> php.ini-max
    - echo extension=php_mbstring.dll >> php.ini-max
    - echo extension=php_fileinfo.dll >> php.ini-max
    - echo extension=php_pdo_sqlite.dll >> php.ini-max
    - echo extension=php_curl.dll >> php.ini-max
    - copy /Y php.ini-max php.ini

    - cd c:\php
    - IF NOT EXIST composer.phar (appveyor DownloadFile https://getcomposer.org/download/1.6.3/composer.phar)
    - php composer.phar self-update
    # copy instead of using echo because appveyor does not allow "%s" characters
    - copy /Y c:\projects\maker-bundle\.appveyor\composer.bat composer.bat

    - cd c:\projects\maker-bundle
    - php -dmemory_limit=-1 c:\php\composer.phar install --no-progress --no-suggest --ansi
    - composer dump-autoload
    - ./vendor/bin/simple-phpunit install

test_script:
    - ./vendor/bin/simple-phpunit --group=functional_group1
    - ./vendor/bin/simple-phpunit --group=functional_group2
    - ./vendor/bin/simple-phpunit --exclude-group=functional_group1,functional_group2
