import React from 'react';
import { Link } from 'react-router-dom';
import logo from '../logo.svg';

const Home = () => {

    return ( <div className="example-wrapper" >
        <h3>Hi! This page is generated by React in your Symfony application! ✅</h3>
        <p className="example-wrapper-code">
            Here is your <Link to="/<?= $app_path ?>">home</Link> page
        </p>
        <div className="logo">
            <img src={logo} alt="logo-create-react-app"/>
        </div>
    </div>);
}

export default Home;