import React from 'react';
<?php if (true === $is_spa): ?>
import Home from './pages/home';
import {
BrowserRouter as Router,
Switch,
Route,
Link
} from "react-router-dom";
import Footer from './components/footer';
<?php endif ?>

const App = () => {
    return (
<?php if (true === $is_spa): ?>
        <Router>
            <Switch>
                <Route path="/<?= $app_path ?>" component={Home} />
            </Switch>
            <Footer />
        </Router>
<?php else: ?>
        <div className="example-wrapper">
            <h3 className="example-wrapper-code">Hi! This page is generated by React in your Symfony application! ✅</h3>
        </div>
<?php endif ?>
    );
}

export default App;
